import json
import pandas as pd
import argparse
import os

def generate_tables(file_path, timeout_mode_filter=None):
    """
    Parses a JSON file generated by prase_dcn_fct.py and prints tables
    for different FCT slowdown metrics, showing their variation with RTO settings.
    """
    if not os.path.exists(file_path):
        print(f"❌ Error: File not found at '{file_path}'")
        return

    print(f"📄 Parsing data from: {os.path.basename(file_path)}")

    with open(file_path, 'r') as f:
        data = json.load(f)

    data_series = data.get("data_series")
    if not data_series:
        print("⚠️ Warning: No 'data_series' found in the JSON file.")
        return

    # Apply timeout_mode filter if provided
    if timeout_mode_filter:
        filtered_series = []
        for series in data_series:
            if series.get("timeout_mode") == timeout_mode_filter:
                filtered_series.append(series)
        data_series = filtered_series
        if not data_series:
            print(f"⚠️ Warning: No data series found for timeout_mode='{timeout_mode_filter}'.")
            return

    # Sort the data series by RTO value in descending order
    try:
        data_series.sort(key=lambda s: int(s.get('rto_high', 0)), reverse=True)
    except (ValueError, TypeError):
        print("⚠️ Warning: Could not sort data series by RTO. Proceeding with original order.")

    # Use flow size buckets from the first series as the table index
    try:
        flow_sizes = data_series[0]["flow_size_buckets_bytes"]
    except (KeyError, IndexError):
        print("⚠️ Warning: Could not find 'flow_size_buckets_bytes' in the first data series.")
        return

    # Define the metrics to be processed into tables
    metrics = [
        "avg_fct_slowdown",
        "p50_fct_slowdown",
        "p80_fct_slowdown",
        "p90_fct_slowdown",
        "p95_fct_slowdown",
        "p99_fct_slowdown",
        "p999_fct_slowdown",
        "tail_fct_slowdown"
    ]

    # Set pandas display options to show all rows and columns
    pd.set_option('display.max_rows', None)
    pd.set_option('display.max_columns', None)
    pd.set_option('display.width', 1000)

    for metric in metrics:
        table_data = {}
        for series in data_series:
            # Ensure the series contains the required metric and RTO info
            if metric in series and 'rto_high' in series and 'rto_low' in series:
                # Create a descriptive column name from RTO values
                column_name = f"RTO={series['rto_high']}/{series['rto_low']}"
                table_data[column_name] = series[metric]

        if not table_data:
            print(f"\n--- No data found for metric: {metric} ---")
            continue

        # Create a DataFrame
        df = pd.DataFrame(table_data)
        df.index = flow_sizes
        df.index.name = "Flow Size (Bytes)"

        # --- Print the formatted table ---
        print("\n" + "="*80)
        # Use a more descriptive title for each table
        metric_title = metric.replace('_', ' ').replace('fct', 'FCT').title()
        print(f"📊 Table for: {metric_title}")
        print("="*80)
        print(df)
        print("="*80 + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Parse FCT JSON data and display tables showing performance vs. RTO.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument(
        'file_path',
        type=str,
        help="Path to the input JSON file."
    )
    parser.add_argument(
        '--timeout_mode',
        type=str,
        default=None,
        help="Optional: Filter data series by 'timeout_mode' (e.g., '1' for slowstart)."
    )
    args = parser.parse_args()

    generate_tables(args.file_path, args.timeout_mode)
