#!/usr/bin/python3
"""
JCT Plotting Script with Ideal JCT Baseline

This script generates JCT vs. Rank plots from JSON data files that include
both experimental results and ideal JCT baselines calculated for AlltoallV
and AllReduce workloads.

Features:
- Reads JSON files generated by parse_jct_with_ideal.py
- Plots experimental JCT results for different algorithms
- Adds ideal JCT reference lines for each message size
- Supports dynamic ideal JCT baselines for different workloads and patterns
- Compatible with existing plotting infrastructure
"""

import argparse
import json
import matplotlib.pyplot as plt
import numpy as np
import os
import glob
from collections import defaultdict

# Import the project's custom plotting library
import lib.py.plot.plot as plot

# Define the desired order of data series in the plot legend and style assignment.
desired_order_for_lossless = [
    "ECMP(NAK+GBN)",
    # "LetFlow(NAK+GBN)",
    "CONGA(NAK+GBN)",
    "ConWeave(NAK+GBN)",
    "DRILL(RTO+GBN)",
    "RPS(RTO+GBN)",
    "AR(RTO+GBN)",
]

desired_order_for_lossy = [
    "ECMP(NAK+SR)",
    # "LetFlow(NAK+SR)",
    "CONGA(NAK+SR)",
    "ConWeave(NAK+SR)",
    "DRILL(RTO+GBN)",
    "RPS(RTO+GBN)",
    "AR(RTO+GBN)",
    # "AR(DCP)",
]

def format_bytes_for_title(num_bytes):
    """Formats a byte count into a human-readable string for plot titles."""
    if num_bytes < 1024:
        return f"{num_bytes}B"
    elif num_bytes < 1024**2:
        return f"{num_bytes/1024:.0f}KB"
    elif num_bytes < 1024**3:
        return f"{num_bytes/1024**2:.0f}MB"
    else:
        return f"{num_bytes/1024**3:.1f}GB"

def draw_jct_plot_with_ideal(json_path, output_dir):
    """
    Reads a single JCT JSON file with ideal JCT data and creates
    'JCT vs. Rank' plots for each message size found.
    """
    with open(json_path, 'r') as f:
        data = json.load(f)

    meta = data.get("metadata", {})
    flow_control = meta.get("flow_control")
    workload_pattern = meta.get("workload_pattern", "uniform")

    if flow_control == "Lossless":
        desired_order = desired_order_for_lossless
    elif flow_control == "Lossy":
        desired_order = desired_order_for_lossy
    else:
        print(f"❌ Error: Unknown flow_control '{flow_control}' in {json_path}. Cannot determine plot order.")
        return

    all_data_series = data.get("data_series", [])
    ideal_jct_data = data.get("ideal_jct_data", {})

    if not all_data_series:
        print(f"Warning: No 'data_series' found in {json_path}.")
        return

    series_by_msg_size = defaultdict(list)
    for series in all_data_series:
        series_by_msg_size[series["message_size_bytes"]].append(series)

    base_name = os.path.splitext(os.path.basename(json_path))[0]

    for msg_size, data_series_list in series_by_msg_size.items():
        print(f"  -> Generating plot for message size: {format_bytes_for_title(msg_size)}")

        series_to_plot = []
        for desired_label in desired_order:
            found_series = None
            for series in data_series_list:
                current_label = f"{series.get('load_balancing_mode', 'N/A')}({series.get('recovery_mechanism', 'N/A')})"
                if current_label == desired_label:
                    found_series = series
                    break

            if found_series:
                series_to_plot.append(found_series)
            else:
                print(f"  ⚠️  Warning: Label '{desired_label}' not found for message size {format_bytes_for_title(msg_size)} in {os.path.basename(json_path)}.")

        if not series_to_plot:
            print(f"  ❌ Error: No drawable data series found for message size {format_bytes_for_title(msg_size)} after filtering.")
            continue

        p = plot.LinePointPlot()
        p.ax.set_xlabel("Group Rank", fontsize=35)
        p.ax.set_ylabel("Average JCT (ms)", fontsize=35)

        # Set title with workload and pattern information
        workload_type = meta.get("load_type", "Unknown")
        title = f"JCT vs. Rank for {workload_type}"
        if workload_pattern != "uniform":
            title += f" ({workload_pattern})"
        title += f" - Message Size: {format_bytes_for_title(msg_size)}"
        p.ax.set_title(title, fontsize=16)

        for series in series_to_plot:
            x_ranks = series["ranks"]
            # Convert y-axis data from µs to ms
            y_jct_us = series["avg_jct_us"]
            y_jct = [y / 1000.0 for y in y_jct_us]

            label = f"{series.get('load_balancing_mode', 'N/A')}({series.get('recovery_mechanism', 'N/A')})"
            num_points = len(x_ranks)
            mark_every_indices = list(range(0, num_points, max(1, num_points // 10)))
            if num_points - 1 not in mark_every_indices:
                mark_every_indices.append(num_points - 1)
            p.plot(x_ranks, y_jct, label=label, markevery=mark_every_indices)

        # Add ideal JCT reference line if available
        msg_size_str = str(msg_size)
        if msg_size_str in ideal_jct_data:
            ideal_info = ideal_jct_data[msg_size_str]
            ideal_jct_us = ideal_info["ideal_jct_us"]
            ideal_workload = ideal_info["workload"]
            ideal_pattern = ideal_info["pattern"]

            # Convert ideal JCT to ms
            ideal_jct_ms = ideal_jct_us / 1000.0

            ideal_label = f'Ideal {ideal_workload}'
            if ideal_pattern != "uniform":
                ideal_label += f' ({ideal_pattern})'
            ideal_label += f': {ideal_jct_ms:.1f} ms'

            p.ax.axhline(
                y=ideal_jct_ms,
                color='red',
                linestyle=':',
                linewidth=3,
                label=ideal_label,
                zorder=200  # Ensure line is on top
            )

            # Calculate and print performance comparison for AR algorithm
            for series in series_to_plot:
                label = f"{series.get('load_balancing_mode', 'N/A')}({series.get('recovery_mechanism', 'N/A')})"
                if label == "AR(RTO+GBN)":
                    y_jct_ms = [y / 1000.0 for y in series["avg_jct_us"]]
                    diffs = [y - ideal_jct_ms for y in y_jct_ms]
                    percents = [(diff / ideal_jct_ms) * 100 for diff in diffs]

                    print(f"  📊 Performance Analysis: {label} vs Ideal ({ideal_workload})")
                    for rank, y_val, diff, pct in zip(series["ranks"], y_jct_ms, diffs, percents):
                        print(
                            f"    Rank {rank}: "
                            f"AR={y_val:.3f} ms, Ideal={ideal_jct_ms:.3f} ms, "
                            f"差值={diff:.3f} ms ({pct:.2f}%)"
                        )

        else:
            print(f"  ⚠️ Warning: No ideal JCT data found for message size {msg_size}")

        p.ax.tick_params(axis='x', labelsize=29)
        p.ax.tick_params(axis='y', labelsize=30)
        legend = p.ax.legend(fontsize=20, loc="upper left")
        legend.set_zorder(100)

        # --- Y-axis range adjustment logic for LINEAR scale (START) ---
        proportion = 0.85

        all_lines = p.ax.get_lines()
        if not all_lines:
            continue

        data_min, data_max = float('inf'), float('-inf')
        for line in all_lines:
            y_data = line.get_ydata()
            if isinstance(y_data, (list, np.ndarray)) and len(y_data) > 0:
                data_min = min(data_min, np.min(y_data))
                data_max = max(data_max, np.max(y_data))

        if data_min == float('inf') or data_max == float('inf') or data_min == data_max:
            continue

        # Calculate range and center in linear space
        data_range = data_max - data_min
        center = (data_max + data_min) / 2

        # Expand range based on proportion
        new_range = data_range / proportion

        # Calculate new limits, ensuring the bottom is not less than 0
        new_bottom = center - (new_range / 2)
        new_top = center + (new_range / 2)

        p.ax.set_ylim(bottom=max(0, new_bottom), top=new_top)
        # --- Y-axis range adjustment logic for LINEAR scale (END) ---

        output_path = os.path.join(output_dir, f"{base_name}_MSG_{msg_size}.pdf")
        plt.savefig(output_path, bbox_inches='tight')
        plt.close()
        print(f"  ✅ JCT plot with ideal baseline saved to: {output_path}")

def main():
    parser = argparse.ArgumentParser(description="Generate JCT vs. Rank plots with ideal JCT baselines from JSON data files.")
    parser.add_argument("input_path", type=str, help="Path to a single JSON file or a directory containing JSON files.")
    args = parser.parse_args()

    input_path = args.input_path

    if os.path.isfile(input_path):
        json_files = [input_path]
        output_dir = os.path.dirname(input_path)
    elif os.path.isdir(input_path):
        json_files = glob.glob(os.path.join(input_path, 'JCT_WITH_IDEAL_*.json'))
        output_dir = input_path
        if not json_files:
            print(f"⚠️ No JSON files starting with 'JCT_WITH_IDEAL_' found in directory: {input_path}")
            return
    else:
        print(f"❌ Error: The provided path is not a valid file or directory: {input_path}")
        return

    print(f"Found {len(json_files)} JSON file(s) with ideal JCT data to process.")
    for json_file in json_files:
        print(f"--- Processing {os.path.basename(json_file)} ---")
        draw_jct_plot_with_ideal(json_file, output_dir)

    print("✅ All files processed.")

if __name__ == '__main__':
    main()