load("@my_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

ARTIFACT_PLOTS = [
    "plot_dcn_fct",
    "plot_dcn_ooo",
    "plot_dcn_pfc_incast",
    "plot_dcn_pfc_trigger",
    "plot_dcn_rto_fct",
    "plot_dcn_rto_fct_trim_vs_rto",
    "plot_dcn_unnecessary_retrans",
    "plot_sim_ai_jct_avg",
    "plot_sim_ai_jct_avg_asy",
    "plot_single_spine_qlen",
]

[
    py_binary(
        name = target,
        srcs = [target + ".py"],
        deps = [
            "//lib/py/plot",
            requirement("matplotlib"),
            requirement("numpy"),
            requirement("pandas"),
        ],
    )
    for target in ARTIFACT_PLOTS
]
