#!/usr/bin/python3
"""
JCT vs. Group Size Plotting Script

Reads JSON files generated by parse_jct_with_ideal.py (--mode vs_groupsize)
and plots JCT slowdown (JCT / Ideal JCT) vs. group size.

Each data series is one (LB, recovery[, CC]) combination.
Error bars show the min and max rank JCT normalized by ideal JCT.
"""

import argparse
import json
import matplotlib.pyplot as plt
import numpy as np
import os
import glob

import lib.py.plot.plot as plot

# ── Label filter ──────────────────────────────────────────────────────────────
# List the exact display labels you want to appear in the plot.
# Leave empty ([]) to show all series.
# Label format: "LB(recovery) [timeout] [/ CC]"
#   e.g. "AR(RTO+GBN) [min]", "AR(RTO+GBN) [1/2]", "ECMP(NAK+SR)"
FILTER_LABELS = [
    # "ECMP(NAK+SR)",
    # "LetFlow(NAK+SR)",
    # "CONGA(NAK+SR)",
    # "ConWeave(NAK+SR)",
    "AR(IdealTrimming)",
    # "AR(RTO+GBN) [1/2]",
    # "AR(RTO+GBN)",
    # "AR(IdealTrimming)",
    "AR(IdealTrimming) [1/2]",
    # "AR(IdealTrimming) [1/4]",
    # "AR(IdealTrimming) [1/8]",
    # "AR(IdealTrimming) [1/16]",
    # "AR(IdealTrimming) [1/32]",
    # "AR(IdealTrimming) [1/64]",
    # "AR(IdealTrimming) [1/128]",
    # "AR(IdealTrimming) [min]",
    # "AR(IdealTrimming)",
    "AR(RTO+GBN) [1/2]",
    "AR(RTO+GBN) [1/4]",
    "AR(RTO+GBN) [1/8]",
    "AR(RTO+GBN) [1/16]",
    "AR(RTO+GBN) [1/32]",
    "AR(RTO+GBN) [1/64]",
    "AR(RTO+GBN) [1/128]",
    "AR(RTO+GBN) [min]",
    # "ECMP(NAK+GBN) / DCQCN",
    # "LetFlow(NAK+GBN) / DCQCN",
    # "CONGA(NAK+GBN) / DCQCN",
    # "ConWeave(NAK+GBN) / DCQCN",
    # "DRILL(RTO+GBN) / DCQCN",
    # "RPS(RTO+GBN) / DCQCN",
    # "AR(RTO+GBN) / DCQCN",
    # "DRILL(RTO+GBN) / NONE",
    # "RPS(RTO+GBN) / NONE",
    # "AR(RTO+GBN) / NONE",
]
# ─────────────────────────────────────────────────────────────────────────────

# Preferred display order — keyed on "LB(base_recovery)" (no timeout, no CC).
DESIRED_ORDER_LOSSY = [
    "ECMP(NAK+SR)",
    "LetFlow(NAK+SR)",
    "CONGA(NAK+SR)",
    "ConWeave(NAK+SR)",
    "AR(IdealTrimming)",
    "AR(RTO+GBN)",
]

DESIRED_ORDER_LOSSLESS = [
    "ECMP(NAK+GBN)",
    "LetFlow(NAK+GBN)",
    "CONGA(NAK+GBN)",
    "ConWeave(NAK+GBN)",
    "DRILL(RTO+GBN)",
    "RPS(RTO+GBN)",
    "AR(RTO+GBN)",
]

# Known timeout suffixes baked into recovery_mechanism by the parser.
_TIMEOUT_SUFFIXES = ["+slowstart", "+1/2", "+1/3", "+1/4", "+1/5"]


def _base_recovery(recovery):
    """Strip timeout suffix from recovery_mechanism to get the base name."""
    for suffix in _TIMEOUT_SUFFIXES:
        if recovery.endswith(suffix):
            return recovery[:-len(suffix)]
    return recovery


def _fmt_timeout(timeout_mode_str):
    """
    Format timeout_mode for display.
      0  -> "" (no timeout, omit)
      1  -> "min"
      n  -> "1/n"
    """
    try:
        n = int(timeout_mode_str)
    except (ValueError, TypeError):
        return ""
    if n == 0:
        return ""
    if n == 1:
        return "min"
    return f"1/{n}"


def _build_display_label(series):
    """
    Build a human-readable label from series fields.
    Format: LB(recovery) [timeout] [/ CC]
      - timeout omitted when 0
      - CC included only when 'congestion_control' key is present
    """
    lb = series.get("load_balancing_mode", "?")
    recovery = _base_recovery(series.get("recovery_mechanism", "?"))
    timeout_str = _fmt_timeout(series.get("timeout_mode", "0"))
    cc = series.get("congestion_control", "")

    label = f"{lb}({recovery})"
    if timeout_str:
        label += f" [{timeout_str}]"
    if cc:
        label += f" / {cc}"
    return label


def _label_base(label):
    """Return the label without the ' / CC' suffix (everything before first ' / ')."""
    return label.split(" / ")[0]


def _display_label(label, filter_labels):
    """
    Return the label as it should appear in the legend.
    - If matched by an exact filter entry → keep label as-is.
    - If matched by a base filter entry (no CC) → strip the CC suffix.
    - If filter_labels is empty → keep label as-is.
    """
    for f in filter_labels:
        if label == f:
            return label
        if " / " not in f and _label_base(label) == f:
            return _label_base(label)
    return label


def _filter_match(label, filter_labels):
    """
    Return True if label matches any entry in filter_labels.
    - Exact match always works.
    - If a filter entry has no ' / ' (no CC part), it also matches any label
      that starts with that entry (i.e. ignores the CC suffix).
    """
    for f in filter_labels:
        if label == f:
            return True
        if " / " not in f and _label_base(label) == f:
            return True
    return False


def _sort_key(series, desired_order):
    """Sort series by desired_order on base 'LB(recovery)', then by timeout, then CC."""
    lb = series.get("load_balancing_mode", "?")
    recovery = _base_recovery(series.get("recovery_mechanism", "?"))
    base = f"{lb}({recovery})"
    try:
        pos = desired_order.index(base)
    except ValueError:
        pos = len(desired_order)
    timeout_val = int(series.get("timeout_mode", "0") or "0")
    cc = series.get("congestion_control", "")
    return (pos, timeout_val, cc)


def draw_jct_vs_groupsize(json_path, output_dir):
    with open(json_path, 'r') as f:
        data = json.load(f)

    meta = data.get("metadata", {})
    flow_control = meta.get("flow_control", "Lossy")
    workload_pattern = meta.get("workload_pattern", "unknown")
    load_type = meta.get("load_type", "Unknown")
    msg_size_name = meta.get("message_size_name", "")

    desired_order = (DESIRED_ORDER_LOSSLESS
                     if flow_control == "Lossless"
                     else DESIRED_ORDER_LOSSY)

    all_series = data.get("data_series", [])
    if not all_series:
        print(f"Warning: No data_series in {json_path}.")
        return

    # When FILTER_LABELS is active it also defines the display order.
    if FILTER_LABELS:
        def _filter_order(s):
            lbl = _build_display_label(s)
            base = _label_base(lbl)
            # Use position of exact match first, then base match
            for i, f in enumerate(FILTER_LABELS):
                if lbl == f:
                    return i
            for i, f in enumerate(FILTER_LABELS):
                if " / " not in f and base == f:
                    return i
            return len(FILTER_LABELS)
        all_series = sorted(all_series, key=_filter_order)
    else:
        all_series = sorted(all_series, key=lambda s: _sort_key(s, desired_order))

    # ── First pass: collect data for all drawable series ─────────────────────
    drawable = []  # list of (label, {group_size: (slowdown, y_lo_err, y_hi_err)})
    for series in all_series:
        label = _build_display_label(series)
        if FILTER_LABELS and not _filter_match(label, FILTER_LABELS):
            continue
        label = _display_label(label, FILTER_LABELS)
        points = series.get("points", [])
        if not points:
            continue

        pts_data = {}
        for pt in points:
            ideal = pt.get("ideal_jct_us")
            jct = pt.get("jct_us")
            all_ranks = pt.get("all_ranks_jct_us", [])
            if ideal is None or ideal == 0 or jct is None:
                continue
            slowdown = jct / ideal
            slowdown_min = min(all_ranks) / ideal if all_ranks else slowdown
            slowdown_max = max(all_ranks) / ideal if all_ranks else slowdown
            pts_data[pt["group_size"]] = (
                slowdown,
                slowdown - slowdown_min,
                slowdown_max - slowdown,
            )

        if not pts_data:
            print(f"  Warning: No valid points for series '{label}' (missing ideal JCT?)")
            continue
        drawable.append((label, pts_data))

    if not drawable:
        print(f"  No drawable series in {os.path.basename(json_path)}, skipping.")
        return

    # ── Grouped bar chart via plot.BarPlot ────────────────────────────────────
    all_group_sizes = sorted({gs for _, pd in drawable for gs in pd})

    p = plot.BarPlot()
    ax = p.ax
    ax.set_xlabel(r"Group Size (\# nodes)", fontsize=35)
    ax.set_ylabel("JCT Slowdown (JCT / Ideal)", fontsize=32)

    title = f"{load_type} ({workload_pattern}) - {msg_size_name} - {flow_control}"
    ax.set_title(title, fontsize=16)

    for label, pts_data in drawable:
        ys   = [pts_data.get(gs, (np.nan,))[0] for gs in all_group_sizes]
        y_lo = [pts_data.get(gs, (np.nan, np.nan))[1] for gs in all_group_sizes]
        y_hi = [pts_data.get(gs, (np.nan, np.nan, np.nan))[2] for gs in all_group_sizes]
        p.insert_yvals(
            ys,
            label=label,
            yerr=[y_lo, y_hi],
            error_kw=dict(elinewidth=1.5, capsize=4, capthick=1.5,
                          ecolor='black', zorder=101),
        )

    p.plot(xlabels=[str(gs) for gs in all_group_sizes])

    # Draw y=1 ideal reference line
    ax.axhline(y=1.0, color='red', linestyle=':', linewidth=2.5,
               label='Ideal (slowdown = 1)', zorder=50)

    ax.tick_params(axis='x', labelsize=26)
    ax.tick_params(axis='y', labelsize=26)

    legend = ax.legend(fontsize=16, loc="center left",
                       bbox_to_anchor=(1.02, 0.5),
                       ncol=1, borderaxespad=0.3)
    legend.set_zorder(200)

    # Y-axis range
    all_ys_flat = [pts_data[gs][0] for _, pts_data in drawable
                   for gs in all_group_sizes if gs in pts_data]
    if all_ys_flat:
        y_lo_lim = max(0, min(all_ys_flat) * 0.95)
        y_hi_lim = max(all_ys_flat) * 1.05
        ax.set_ylim(bottom=y_lo_lim, top=y_hi_lim)

    base_name = os.path.splitext(os.path.basename(json_path))[0]
    output_path = os.path.join(output_dir, f"{base_name}.pdf")
    plt.savefig(output_path, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Plot JCT slowdown vs. group size from JCT_VS_GROUPSIZE_*.json files.")
    parser.add_argument("input_path", type=str,
                        help="Path to a single JSON file or directory containing JSON files.")
    args = parser.parse_args()

    input_path = args.input_path
    if os.path.isfile(input_path):
        json_files = [input_path]
        output_dir = os.path.dirname(input_path) or "."
    elif os.path.isdir(input_path):
        json_files = glob.glob(os.path.join(input_path, 'JCT_VS_GROUPSIZE_*.json'))
        output_dir = input_path
        if not json_files:
            print(f"No JCT_VS_GROUPSIZE_*.json files found in: {input_path}")
            return
    else:
        print(f"Error: not a valid file or directory: {input_path}")
        return

    if FILTER_LABELS:
        print(f"Filter (from FILTER_LABELS): {FILTER_LABELS}")

    print(f"Found {len(json_files)} file(s).")
    for json_file in sorted(json_files):
        print(f"--- {os.path.basename(json_file)} ---")
        draw_jct_vs_groupsize(json_file, output_dir)

    print("Done.")


if __name__ == '__main__':
    main()
