#!/usr/bin/env python3
"""Generate a container SSH config and a sourceable host environment file."""
import argparse
import os
from pathlib import Path
import re
import shlex
import stat
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
HEADER = """# Generated by testbed/setup_ssh.sh. Paths below are inside the container.
Host *
  UserKnownHostsFile /run/artifact-ssh/known_hosts
  StrictHostKeyChecking yes
  BatchMode yes
  ForwardAgent no
  ConnectTimeout 10
  IdentityAgent /run/artifact-agent.sock
  IdentityFile none
  IdentitiesOnly no
  ControlMaster no
  ControlPath none

"""


def container_config(source):
    lines = []
    # Authentication and connection sharing belong to the generated container config.
    removed = {'identityfile', 'identityagent', 'identitiesonly', 'certificatefile',
               'controlmaster', 'controlpath', 'controlpersist'}
    for number, line in enumerate(source.splitlines(), 1):
        stripped = line.strip()
        if not stripped or stripped.startswith('#'):
            lines.append(line)
            continue
        key = re.split(r'[\s=]+', stripped, maxsplit=1)[0].lower()
        if key == 'include':
            raise ValueError(f'SSH config line {number}: flatten Include files before setup; '
                             'only one config file is mounted into the container')
        if key == 'match':
            raise ValueError(f'SSH config line {number}: provide a config using Host blocks; '
                             'Match rules may depend on the host environment')
        if key not in removed:
            lines.append(line)
    return HEADER + '\n'.join(lines) + '\n'


def write_private(path, content):
    # Atomic replacement keeps a failed invocation from leaving a partial file.
    fd, temporary = tempfile.mkstemp(prefix='.' + path.name, dir=path.parent)
    try:
        with os.fdopen(fd, 'w') as stream:
            stream.write(content)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ssh-config', type=Path, default=Path.home() / '.ssh/config')
    parser.add_argument('--known-hosts', type=Path, default=Path.home() / '.ssh/known_hosts')
    parser.add_argument('--deployment', type=Path, default=ROOT / 'deployment/deployment.local.yaml')
    parser.add_argument('--output-dir', type=Path, default=Path.home() / '.config/revisitps-artifact')
    args = parser.parse_args()
    if not args.deployment.is_absolute():
        args.deployment = ROOT / args.deployment
    source, known, deployment, output = [p.expanduser().resolve() for p in
        (args.ssh_config, args.known_hosts, args.deployment, args.output_dir)]
    for path in (source, known, deployment):
        if not path.is_file() or not os.access(path, os.R_OK):
            parser.error(f'Readable file required: {path}')
    if {source, known, deployment} & {output / 'ssh_config', output / 'env.sh'}:
        parser.error('Input files must differ from generated output files')
    agent = os.environ.get('SSH_AUTH_SOCK') or os.environ.get('ARTIFACT_AGENT_SOCKET', '')
    if not agent or not Path(agent).exists() or not stat.S_ISSOCK(os.stat(agent).st_mode):
        parser.error('Start a dedicated agent and load your key first: '
                     'eval "$(ssh-agent -s)"; ssh-add /path/to/original_key')
    identities = subprocess.run(['ssh-add', '-l'], env={**os.environ, 'SSH_AUTH_SOCK': agent},
                                capture_output=True, text=True)
    if identities.returncode:
        parser.error('Agent is inaccessible or has no identities: ' + identities.stderr.strip())
    config = container_config(source.read_text())
    output.mkdir(parents=True, exist_ok=True, mode=0o700)
    values = {
        'ARTIFACT_AGENT_SOCKET': str(Path(agent).absolute()),
        'ARTIFACT_SSH_CONFIG_PATH': str(output / 'ssh_config'),
        'ARTIFACT_KNOWN_HOSTS_PATH': str(known),
        'ARTIFACT_DEPLOYMENT_PATH': str(deployment),
    }
    write_private(output / 'ssh_config', config)
    write_private(output / 'env.sh', '# Generated host-local settings; rerun setup after replacing the agent.\n'
                  + ''.join(f'export {key}={shlex.quote(value)}\n' for key, value in values.items()))
    print('Loaded identities (configure ssh.expected_fingerprints in deployment.local.yaml):')
    print(identities.stdout.rstrip())
    print('\nApply settings in your current terminal:\n  source ' + shlex.quote(str(output / 'env.sh')))
    print('\nIf an artifact container already exists, recreate it between experiments to refresh mounts.\n'
          'This script does not stop containers, modify known_hosts, or contact devices.')


if __name__ == '__main__':
    try:
        main()
    except (OSError, ValueError) as exc:
        raise SystemExit(f'setup_ssh: {exc}')
