package(default_visibility = ["//visibility:public"])
load("@my_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "flowmonitor",
    srcs = ["flowmonitor.py"],
    deps = [
        requirement("numpy"),
        requirement("pandas"),
    ],
)
